# .github/workflows/git-sync.yml
# mirror repo --> main repo

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: sig-alanyan/git-sync
        with:
          source_repo: "git@github.com:sig-alanyan/platform-samples.git"
          source_branch: "master"
          destination_repo: "git@github.com:sig-alanyan/platform-samples-mirror.git"
          destination_branch: "master"
#          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
